### ISSUE TITLE
cannot install theme from github private repo

### ISSUE THREAD

**Issue by ttskch** [getshifter/shifter-install-helper#5]
Thanks for your awesome service!

I'm trying to install my own theme from github private repo but following error is occurring and I cannot complete installation.

```
There has been a critical error on your website. Please check your site admin email inbox for instructions.
```

I'm filling `GitHub token (option)` field with my personal access token of github and it checked ALL scopes just in case.

FYI, if I just make the github repo PUBLIC, I can install it correctly.

Do you have some advices?

Thanks.

In Japanese below.

素晴らしいサービスのご提供ありがとうございます。

管理画面の `外観 > Add New from GitHub` で自作のテーマをgithubのプライベートリポジトリからインストールしようとすると、

```
サイトに重大なエラーがありました。 詳細については、サイト管理者のメール受信ボックスを確認してください。
```

というエラーになります。

`GitHub token (option)` 蘭にはgithubで発行したpersonal access tokenを入力しており、そのtokenには念のためすべてのスコープを付与してあります。

また、テーマのリポジトリをpublicにするだけでインストールは正常に成功するようになります。

どういった原因が考えられますでしょうか？

**Comment by wokamoto** [comment]
このプラグインは、Git リポジトリを clone したり Git リポジトリから pull したりするのではなく、GitHub の[リリース機能](https://help.github.com/ja/github/administering-a-repository/creating-releases)に添付されたパッケージをダウンロードしてきて WordPress にプラグイン/テーマをインストール/更新する機能を提供しています。
（そのため GitHub 以外の git リポジトリを元にすることはできません）

[README](https://github.com/getshifter/shifter-github/blob/master/README.md)にも記載していますが、Tag付けをしてリリースパッケージを添付する必要があります。
手動でリリースパッケージを作成するには以下の手順で実施していただけば良いです。

A. Manually release the new version.
 1. Please visit "releases" in your GitHub repository.
 1. Choose a tag.
 1. Fill out the release note and title.
 1. Upload your plugin which is comporessed with zip. (Optional)
 1. Press "Publish release".

また、README には [GitHub Actions](https://help.github.com/ja/actions/automating-your-workflow-with-github-actions/about-github-actions)を使用してタグづけされたら[自動的にリリースパッケージを作成する手順](https://github.com/getshifter/shifter-github#b-automated-release-the-new-version-with-github-actions)も記載してありますので、そちらも参照してください。

こちらの操作を行なっていない GitHub のリポジトリを元にインストール/更新することができません。
ただし Public リポジトリの場合、パッケージを作成しなくても zip をダウンロードすることができる URL が提供されているので、そちらからダウンロードしてきてインストールを実施することができますが、バージョン管理ができないので、タグ付けとリリースパッケージ作成を行なってください。

**Comment by ttskch** [comment]
@wokamoto 早速のご返信ありがとうございます！

ご説明いただいた内容、理解できました。

が、手順通りに実施してもやはり同様のエラーになってしまいました。

**やったこと**

1. githubのprivateリポジトリ（ https://github.com/<user>/<repo> ）にテーマのソースコード一式をpush
1. `git tag 1.0.0`
1. `git push origin 1.0.0`
1. https://github.com/<user>/<repo>/tags にアクセス
1. `1.0.0` の右端の `...` ボタンから `Create release` をクリック
1. `Publish release` をクリック
1. https://github.com/settings/tokens で全部のスコープにチェックを入れたアクセストークンを生成
1. wordpress管理画面の `GitHub repo URL` に `https://github.com/<user>/<repo>` を入力
1. 同じく `GitHub token (option)` にアクセストークンを入力
1. `今すぐインストール` をクリック
1. `サイトに重大なエラーがありました。 詳細については、サイト管理者のメール受信ボックスを確認してください。` となる

https://github.com/ttskch/shifter-theme-test
こちらのprivateリポジトリに適当なテンプレートを入れて同様の手順を試してみても再現しましたので、 @wokamoto 様をcollaboratorに招待してみました。必要でしたら確認してみていただければと思います。

**Comment by wokamoto** [comment]
確認しました。以下の手順が行われていません。
> 4.Upload your plugin which is comporessed with zip. (Optional)

手動で zip ファイルを添付する場合は、https://github.com/ttskch/shifter-theme-test/releases/edit/1.0.0 からテーマファイル一式を zip で固めたファイルを添付してください。
私の方で実施してみましたので、これを元に Shifter にインストールしてみてください。

**Comment by wokamoto** [comment]
また、上のコメントでも説明しておりますが、このリリースパッケージに添付する zip ファイルは GitHub Actions などを使えばタグづけされた時に自動で作成して添付することが可能です。
設定方法に関しては README をご確認ください。

**Comment by ttskch** [comment]
@wokamoto わざわざご確認いただきありがとうございました！手順理解できました 🙏こちらでもインストールを確認できました。引き続きよろしくお願いします！
