### ISSUE TITLE
cannot delete theme installed from github repo

### ISSUE THREAD

**Issue by ttskch** [getshifter/shifter-install-helper#6]
I've installed my own theme from github public repo. (Installation from private repo is failed as I mentioned in #5)

When I try to delete this theme, following error occurs and deletion isn't completed.

```
Deletion failed: The requested theme does not exist.
```

FYI, I can delete correctly some other themes which is installed via regular dashboard feature.

Do you have some advices?

Thanks.

In Japanese below.

githubのpublicリポジトリからインストールした自作テーマを、管理画面から削除しようとすると、以下のエラーとなり削除できません。

```
削除に失敗しました: 選択したテーマはありません。
```

github経由でなく普通にインストールしたテーマは問題なく削除できます。

どんな原因が考えられますでしょうか？

**Comment by wokamoto** [comment]
ちょっと原因がわからないです。
可能であれば、このエラーが発生するテーマの github のリポジトリの URL をご連絡いただけますでしょうか？
確認してみます。

**Comment by ttskch** [comment]
@wokamoto 
早速のご返信ありがとうございます！

ただ、有料テーマを元にしたもので、権利元によって公開が制限されているためリポジトリをお見せすることができません :bow:

#5 の調査の一環で一時的にpublicにしてインストールしてみたものになります。

サイト自体を削除してやり直してみます :pray:
